version: "3.8"

services:
  file-comparison-api:
    build: .
    env_file:
      - .env
    volumes:
      - ~/.aws:/home/appuser/.aws
    ports:
      - 5000:5000
    command: uvicorn app.src.main:app --host 0.0.0.0 --port 5000