name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

env:
  PIPENV_VENV_IN_PROJECT: 1

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run test suite
        run: pipenv -m unittest -v

